# Generated by Django 5.2.4 on 2025-08-04 17:42
from django.db import migrations

def crear_categorias_iniciales(apps, schema_editor):
    Categoria = apps.get_model('gestor_gastos', 'Categoria')
    categorias = [
        'Alimentación',
        'Transporte', 
        'Entretenimiento',
        'Servicios',
        'Salud',
        'Educación',
        'Compras',
        'Otros'
    ]
    
    for nombre_categoria in categorias:
        Categoria.objects.get_or_create(nombre=nombre_categoria)

def eliminar_categorias(apps, schema_editor):
    Categoria = apps.get_model('gestor_gastos', 'Categoria')
    Categoria.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('gestor_gastos', '0002_auto_20250701_1637'),
    ]
    operations = [
        migrations.RunPython(crear_categorias_iniciales, eliminar_categorias),
    ]
