# Generated by Django 5.1.5 on 2025-08-04 15:26

from django.db import migrations

def eliminar_categoria_otros_gastos(apps, schema_editor):
    Categoria = apps.get_model('gestor_gastos', 'Categoria')
    # Usamos filter().delete() para no fallar si la categoría no existe
    Categoria.objects.filter(nombre='Otros Gastos').delete()

def anadir_categoria_otros_gastos(apps, schema_editor):
    Categoria = apps.get_model('gestor_gastos', 'Categoria')
    # Usamos get_or_create para no duplicar si la categoría ya existe
    Categoria.objects.get_or_create(nombre='Otros Gastos')

class Migration(migrations.Migration):

    dependencies = [
        ('gestor_gastos', '0003_auto_20250804_1342'),
    ]

    operations = [
        migrations.RunPython(eliminar_categoria_otros_gastos, reverse_code=anadir_categoria_otros_gastos),
    ]