# Generated by Django 5.1.5 on 2025-08-04 15:26

from django.db import migrations

CATEGORIAS_A_ELIMINAR = [
    'Alimentación',
    'Compras',
    'Educación',
    'Entretenimiento',
    'Otros Servicios',
    'Otros Gastos',
    'Otros', # De la migración 0003
    'Servicios', # De la migración 0003
]

def eliminar_categorias_no_deseadas(apps, schema_editor):
    Categoria = apps.get_model('gestor_gastos', 'Categoria')
    Categoria.objects.filter(nombre__in=CATEGORIAS_A_ELIMINAR).delete()

def anadir_categorias_no_deseadas(apps, schema_editor):
    Categoria = apps.get_model('gestor_gastos', 'Categoria')
    for nombre in CATEGORIAS_A_ELIMINAR:
        Categoria.objects.get_or_create(nombre=nombre)

class Migration(migrations.Migration):

    dependencies = [
        ('gestor_gastos', '0003_auto_20250804_1342'),
    ]

    operations = [
        migrations.RunPython(eliminar_categorias_no_deseadas, reverse_code=anadir_categorias_no_deseadas),
    ]
